### PR TITLE
Create rust.yml

### PR DESCRIPTION
**Pull request by mack-stefan**
Automatically build and test project on pull requests to the default branch and the development branch

### CODE REVIEW

**Review by henriklovhaug — APPROVED** [review]
LGTM

**Comment by mack-stefan** [comment]
> LGTM

No, it crashes

**Comment by henriklovhaug** [comment]
oja

**Comment by mack-stefan** [comment]
Now it's not running because development isn't a protected branch. Please set main and development to be protected, or allow me to do so.

**Comment by mack-stefan** [comment]
Reopen this when branches are protected @henriklovhaug

**Comment by henriklovhaug** [comment]
Should be fixed

**Pull request merged**
