### PR TITLE
Add UI to UI CD

### PR DESCRIPTION
**Pull request by mack-stefan**

### CODE REVIEW

**Comment by mack-stefan** [comment]
@henriklovhaug Please fix the rust error

**Comment by henriklovhaug** [comment]
Rust test works locally, looking into error now

**Comment by henriklovhaug** [comment]
@Areskiko Unit-tests are running twice?

**Comment by mack-stefan** [comment]
> @Areskiko Unit-tests are running twice? 

We can turn it off, but the default npm test action tests against a couple of node versions

**Comment by mack-stefan** [comment]
Nvm I see it now

**Pull request merged**
